name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.stack') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Stack
        uses: freckle/stack-action@v4
        with:
          test: true

          # Too pedantic: enables -Werror and warnings that we don’t want (e.g.
          # incomplete uni patterns)
          pedantic: false

          # Instead, add only -Werror
          stack-arguments: --ghc-options -Werror

      - name: "Haddock: build"
        # Not sure why it’s not $(stack path --local-doc-root) but the generated
        # directory isn’t right, reproducible locally. Haddock reports
        # a different one at the end of its run, and *that* is where the
        # documentation is.
        run: |
          stack haddock --fast --test --no-run-tests --no-haddock-deps
          echo "haddock_files=$(stack path --local-install-root)/doc/" >> "$GITHUB_ENV"
          echo "stack path --local-install-root: $(stack path --local-install-root)"

      - name: "Haddock: package"
        uses: actions/upload-pages-artifact@v1 # This will automatically upload an artifact from the '/_site' directory
        with:
          path: ${{ env.haddock_files }}

      - name: "Haddock: deploy"
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@main
